package com.example.memorygame2.utils

import com.example.memorygame2.R

val DEF_ICON= listOf(
    R.drawable.ic_clock ,
    R.drawable.ic_face1,
    R.drawable.ic_cloud,
    R.drawable.ic_glass,
    R.drawable.ic_jogi,
    R.drawable.ic_key,
    R.drawable.ic_leafs,
    R.drawable.ic_palne,
    R.drawable.ic_star,
    R.drawable.ic_train,
    R.drawable.ic_tree,
    R.drawable.ic_watch,
    R.drawable.ic_thunder,
    R.drawable.ic_cycle,
    R.drawable.ic_mobile,
    R.drawable.ic_tv,
    R.drawable.ic_pest,
    R.drawable.ic_scooter,
    R.drawable.ic_mask,
    R.drawable.ic_mail,
    R.drawable.ic_dollar,
    R.drawable.ic_nature_people,
    R.drawable.ic_bell,
    R.drawable.ic_bbq,
    R.drawable.ic_rat,
    R.drawable.ic_psyco,
    R.drawable.ic_soccer,
    R.drawable.ic_helmate,
    R.drawable.ic_storefront,
    R.drawable.ic_tram,
    R.drawable.ic_sun,
    R.drawable.ic_bulb,
    R.drawable.ic_brifcase,
    R.drawable.ic_traffic,
    R.drawable.ic_bike,
    R.drawable.ic_sofa,
    R.drawable.ic_umbrella,
    R.drawable.ic_stopwatch,
    R.drawable.ic_gloves,
    R.drawable.ic_hills
)